name: Actions Workflow

on: 
  push:
    # branches:
    #   - master
    #   - test
    #   - 'feature/*' # feature/anything
    #   - 'feature/**' # feature/anything/nested/deeply
    #   - '!feature/featc' # exclude feature/featc
    # branches-ignore:
    #   - master
    tags:
      - 'v1.*' # v1.anything
    paths:
      - '**.js'
      - '!filename.js' # exclude filename.js

    # paths-ignore:
    #   - 'docs/**'
    
  # repository_dispatch:
  #   types: [build]
  # schedule:
  #   - cron: "0/5 * * * *" #
  #   - cron: "0/5 * * * *" #
  # push:
  pull_request:
    types:
      - closed
      - assigned
      - opened
      - reopened

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{github.event.client_payload.env}}
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{github.token}}
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files after checkout
        run: |
          pwd
          ls -a
      - name: Simple Js Actions
        id: greeting
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Renish'
      - name: Log Greeting Time
        run: echo "Greeting time was ${{steps.greeting.outputs.time}}"
  