name: Container Workflow

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image:  node:20-alpine
        ports:
          - 3001:3000
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    # container:
    #   image: node:20-alpine
    steps:
      - name: Post a user
        run: |
          curl -X POST http://localhost:3001/api/user -H "Content-Type: application/json" -d '{"username": "Renish123", "address":"rajkot123"}'
      - name: Get all users
        run: |
          curl http://localhost:3001/api/users

# this file to be continued
# more edits to be done in future
# and in this code there is some issued to run docker container services in github actions
# so try to fix that issue in future edits
# now continued git and github bootcamp course


