name: ENV Variables
on: 
  - push
env:
  WF_ENV: Available to all jobs

jobs: 
  log-env:
    runs-on: ubuntu-latest
    env: 
      JOB_ENV: Available to all steps in this job
    steps:
      - name: Log ENV variable
        env:
          STEP_ENV: Available to this step only
        run: |
          echo "WF_ENV is $WF_ENV"
          echo "JOB_ENV is $JOB_ENV"
          echo "STEP_ENV is $STEP_ENV"
      - name: Log ENV 2 variable again
        run: |
          echo "WF_ENV is $WF_ENV"
          echo "JOB_ENV is $JOB_ENV"
          echo "STEP_ENV is $STEP_ENV"

